### ISSUE TITLE
Migrator terminates

### ISSUE THREAD

**Issue by erazor-de** [giladreich/ida_migrator#1]
I'm using the latest IDA 7.6.210427 on Linux.
When I start IDA or load a database with your plugin installed it loads the plugin but instantly terminates it. The output in the console is

    [IDA Migrator]: Successfully loaded IDA Migrator plugin.
    [IDA Migrator]: term

How can I help you debug this issue?

**Comment by giladreich** [comment]
Hi @erazor-de,

Many thanks for reporting!

This is expected to see this log message when loading IDA without database, but not a friendly behavior indeed, hence I made an update for this and more improvements: https://github.com/giladreich/ida_migrator/releases/tag/2.0.0

Let me know if it works now or if other issues appear; a callstack would be very much appreciated.

**Comment by erazor-de** [comment]
Thanks for the new version. As it didn't work I had a look at the source and found that you are checking init_hexrays_plugin() and that's the reason it doesn't work for me. I was not aware that this plugin needs the decompiler. As transferring enums, structures and function names would make even sense for users without decompiler maybe limited functionality could be provided in this case?

**Comment by giladreich** [comment]
> As it didn't work I had a look at the source and found that you are checking init_hexrays_plugin() and that's the reason it doesn't work for me.

Which IDA edition are you using? I thought that only IDA Pro edition supports Python API from what I last checked, hence the check:
```python
    def init(self):
        if not idaapi.init_hexrays_plugin():
            return idaapi.PLUGIN_SKIP

        log_info("Successfully loaded plugin - v{}", VERSION)
        return idaapi.PLUGIN_KEEP
```

To check that the plugin is compatible with hex-rays decompiler, since only IDA Pro at the time I was writing this plugin was having the decompiler. Now there is also IDA Home edition, but it should also have the hex-rays decompiler.

> As transferring enums, structures and function names would make even sense for users without decompiler maybe limited functionality could be provided in this case?

That would have been an ideal situation if all IDA editions would have supported the IDA Python API.

**Comment by erazor-de** [comment]
I have IDA Pro, but without any decompiler plugin (I don't need it and they are way to expensive for a hobbyist). The only thing I can say about the home edition is that it has access to an online decompiler.
If any IDA can execute the plugin up to this point it definitely supports the python api I would say?

**Comment by giladreich** [comment]
Interesting and thank you for your answer!
In that case, if it worked for you without the check, we can remove it. Happy to receive a PR from you if you could kindly send one please and also bump the patch version to 2.0.1.

**Comment by giladreich** [comment]
Many thanks, @erazor-de for taking the time to post the PR! :)

https://github.com/giladreich/ida_migrator/releases/tag/2.0.1
